### ISSUE TITLE
Mix of English and German

### ISSUE THREAD

**Issue by sixtyfive** [Jomula/livinghabil#1]
A proper translation of "Arabistik" into English does exist, they call it "Arabic Studies" :)

P.S., https://jomula.github.io/livinghabil/assets/images/dev_prof_97-23.png is real interesting to look at. Do we know how to explain the synchronicity between the different institutes? Especially the spooky cliff that drops off between 2010 and 2011... real curious.

**Comment by Jomula** [comment]
Yep I know, but there is a different tone in "Arabic Studies" than in "Arabistik", as the latter is much more grounded in the German "-istik" academic tradition and thus feels more "traditional".

Regarding the plot: That is indeed interesting and I was going to look at the reasons for that drop some time in the future :-)

**Comment by sixtyfive** [comment]
In that case, fair enough! As someone who was not exactly encouraged to bring forward any kind of critique about the way things were being done and things were being seen - thank you!

I'll star your repo in the hopes of finding out about your findings :)
